""" ComfoConnect Property definitions. """

from dataclasses import dataclass

from .const import UNIT_NODE, UNIT_NODECONFIGURATION, UNIT_TEMPHUMCONTROL

TYPE_PROP_STRING = 0x10


@dataclass
class Property:
    unit: int
    subunit: int
    type: int
    id: int


PROPERTY_SERIAL_NUMBER = Property(UNIT_NODE, 0x01, TYPE_PROP_STRING, 0x04)
PROPERTY_MODEL = Property(UNIT_NODE, 0x01, TYPE_PROP_STRING, 0x08)
PROPERTY_ARTICLE = Property(UNIT_NODE, 0x01, TYPE_PROP_STRING, 0x0B)
PROPERTY_COUNTRY = Property(UNIT_NODE, 0x01, TYPE_PROP_STRING, 0x0D)

PROPERTY_MAINTAINER_PASSWORD = Property(UNIT_NODECONFIGURATION, 0x01, TYPE_PROP_STRING, 0x03)

PROPERTY_SENSOR_VENTILATION_TEMP_PASSIVE = Property(UNIT_TEMPHUMCONTROL, 0x01, TYPE_PROP_STRING, 0x04)
PROPERTY_SENSOR_VENTILATION_HUMIDITY_COMFORT = Property(UNIT_TEMPHUMCONTROL, 0x01, TYPE_PROP_STRING, 0x06)
PROPERTY_SENSOR_VENTILATION_HUMIDITY_PROTECTION = Property(UNIT_TEMPHUMCONTROL, 0x01, TYPE_PROP_STRING, 0x07)